# Generated by Django 3.2.15 on 2022-09-14 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ['-created'], 'verbose_name': 'Property', 'verbose_name_plural': 'Properties'},
        ),
        migrations.AlterField(
            model_name='property',
            name='address',
            field=models.TextField(max_length=512),
        ),
        migrations.AlterField(
            model_name='property',
            name='contact_info',
            field=models.CharField(blank=True, help_text='Your default phone number or email will be used if this field is not filled.', max_length=255, verbose_name='Contact number or email (optional)'),
        ),
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='property',
            name='google_maps',
            field=models.URLField(blank=True, max_length=512, verbose_name='Google maps link (optional)'),
        ),
        migrations.AlterField(
            model_name='property',
            name='image',
            field=models.ImageField(null=True, upload_to='uploads/properties/%Y/%m/', verbose_name='Image'),
        ),
    ]
