# Generated by Django 3.2.15 on 2022-10-15 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_land_road_accessible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='bathroom',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('4+', '4+')], default='1', max_length=20, verbose_name='Bathrooms'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='bedroom',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('4+', '4+')], default='1', max_length=20, verbose_name='Bedrooms'),
        ),
        migrations.AlterField(
            model_name='house',
            name='bathroom',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('4+', '4+')], default='1', max_length=20, verbose_name='Bathrooms'),
        ),
        migrations.AlterField(
            model_name='house',
            name='bedroom',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('4+', '4+')], default='1', max_length=20, verbose_name='Bedrooms'),
        ),
        migrations.AlterField(
            model_name='villa',
            name='bathroom',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('4+', '4+')], default='1', max_length=20, verbose_name='Bathrooms'),
        ),
        migrations.AlterField(
            model_name='villa',
            name='bedroom',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('4+', '4+')], default='1', max_length=20, verbose_name='Bedrooms'),
        ),
    ]
